const versions = {
	kanto: ["red", "blue", "yellow", "fireRed", "leafGreen"],
	originalJohto: ["gold", "silver", "crystal"],
	hoenn: ["ruby", "sapphire", "emerald"],
	originalSinnoh: ["diamond", "pearl", "platinum"],
	updatedJohto: ["heartGold", "soulSilver"],
	originalUnova: ["black", "white"],
	updatedUnova: ["blackTwo", "whiteTwo"],
	kalosMountain: ["x", "y"],
	updatedHoenn: ["omegaRuby", "alphaSapphire"],
	originallola: ["sun", "moon"],
	updatedAlola: ["ultraSun", "ultraMoon"],
	letsgoKanto: ["letsGoPikachu", "letsGoEevee"], 
	galar: ["sword", "shield"],
	extendedSinnoh: ["brilliantDiamond", "shiningPearl"],
	hisui: ["legendsArceus"],
	paldea: ["scarlet", "violet"]
}

export const expansions = {
	genEight: ["isleOfArmor", "crownTundra"],
	genNine: [{ name: "tealMask", route: "kitakami" }, { name: "indigoDisk", route: "blueberry" }]
}

export const legendaries = {
	red: ["articuno", "zapdos", "moltres", "mewtwo"],
	blue: ["articuno", "zapdos", "moltres", "mewtwo"],
	yellow: ["articuno", "zapdos", "moltres", "mewtwo"],
	gold: ["raikou", "entei", "suicune", "lugia", "ho-oh"],
	silver: ["raikou", "entei", "suicune", "lugia", "ho-oh"],
	crystal: ["raikou", "entei", "suicune", "lugia", "ho-oh", "celebi"],
	ruby: ["regirock", "regice", "registeel", "latios", "groudon", "rayquaza"],
	sapphire: ["regirock", "regice", "registeel", "latias", "kyogre", "rayquaza"],
	emerald: ["regirock", "regice", "registeel", "latias", "latios", "kyogre", "groudon", "rayquaza"],
	fireRed: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune"],
	leafGreen: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune"],
	diamond: ["dialga", "heatran", "regigigas", "giratina", "cresselia", "mesprit", "uxie", "azelf"],
	pearl: ["palkia", "heatran", "regigigas", "giratina", "cresselia", "mesprit", "uxie", "azelf"],
	platinum: ["articuno", "zapdos", "moltres", "dialga", "palkia", "heatran", "regigigas", "giratina", "cresselia", "mesprit", "uxie", "azelf"],
	heartGold: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune", "lugia", "ho-oh", "latias", "kyogre", "rayquaza"],
	soulSilver: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune", "lugia", "ho-oh", "latios", "groudon", "rayquaza"],
	black: ["cobalion", "terrakion", "virizion", "tornadus", "reshiram", "landorus", "kyurem"],
	white: ["cobalion", "terrakion", "virizion", "thundurus", "zekrom", "landorus", "kyurem"],
	blackTwo: ["regirock", "regice", "registeel", "latios", "mesprit", "uxie", "azelf", "heatran", "regigigas", "cresselia", "cobalion", "terrakion", "virizion", "tornadus", "thundurus", "zekrom", "landorus", "kyurem"],
	whiteTwo: ["regirock", "regice", "registeel", "latias", "mesprit", "uxie", "azelf", "heatran", "regigigas", "cresselia", "cobalion", "terrakion", "virizion", "tornadus", "thundurus", "reshiram", "landorus", "kyurem"],
	x: ["articuno", "zapdos", "moltres", "mewtwo", "xerneas", "zygarde"],
	y: ["articuno", "zapdos", "moltres", "mewtwo", "yveltal", "zygarde"],
	omegaRuby: ["raikou", "entei", "suicune", "ho-oh", "regirock", "regice", "registeel", "latios", "latias", "groudon", "rayquaza", "deoxys", "mesprit", "uxie", "azelf", "palkia", "heatran", "regigigas", "cresselia", "giratina", "cobalion", "terrakion", "virizion", "tornadus", "reshiram", "landorus", "kyurem"],
	alphaSapphire: ["raikou", "entei", "suicune", "lugia", "regirock", "regice", "registeel", "latios", "latias", "kyogre", "rayquaza", "deoxys", "mesprit", "uxie", "azelf", "palkia", "heatran", "regigigas", "cresselia", "giratina", "cobalion", "terrakion", "virizion", "thundurus", "zekrom", "landorus", "kyurem"],
	sun: ["zygarde", "type-null", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "solgaleo", "necrozma"],
	moon: ["zygarde", "type-null", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "lunala", "necrozma"],
	ultraSun: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune", "ho-oh", "regirock", "regice", "registeel", "latios", "groudon", "rayquaza", "mesprit", "uxie", "azelf", "dialga", "heatran", "giratina", "cresselia", "cobalion", "terrakion", "virizion", "tornadus", "reshiram", "landorus", "kyurem", "xerneas", "zygarde", "type-null", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "solgaleo", "necrozma"],
	ultraMoon: ["articuno", "zapdos", "moltres", "mewtwo", "raikou", "entei", "suicune", "lugia", "regirock", "regice", "registeel", "latias", "kyogre", "rayquaza", "mesprit", "uxie", "azelf", "palkia", "regigigas", "giratina", "cresselia", "cobalion", "terrakion", "virizion", "thundurus", "zekrom", "landorus", "kyurem", "yvetal", "zygarde", "type-null", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "lunala", "necrozma"],
	letsGoPikachu: ["articuno", "zapdos", "moltres", "mewtwo"],
	letsGoEevee: ["articuno", "zapdos", "moltres", "mewtwo"],
	sword: ["type-null", "zacian", "eternatus"],
	shield: ["type-null", "zamazenta", "eternatus"],
	isleOfArmor: ["kubfu"],
	crownOfTundra: {
		sword: ["articuno-g", "zapdos-g", "moltres-g", "mewtwo", "raikou", "entei", "suicune", "ho-oh", "regirock", "regice", "registeel", "latios", "groudon", "rayquaza", "mesprit", "uxie", "azelf", "dialga", "heatran", "giratina", "regigigas", "giratina", "cresselia", "cobalion", "terrakion", "virizion", "tornadus", "landorus", "reshiram", "kyurem", "keldeo", "xerneas", "zygarde", "solgaleo", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "regieleki", "regidrago", "glastrier", "spectrier", "calyrex"],
		shield: ["articuno-g", "zapdos-g", "moltres-g", "mewtwo", "raikou", "entei", "suicune", "lugia", "regirock", "regice", "registeel", "latias", "kyogre", "rayquaza", "mesprit", "uxie", "azelf", "palkia", "heatran", "giratina", "regigigas", "giratina", "cresselia", "cobalion", "terrakion", "virizion", "thundurus", "landorus", "zekrom", "kyurem", "keldeo", "yvetal", "zygarde", "lunala", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "regieleki", "regidrago", "glastrier", "spectrier", "calyrex"]
	},
	brilliantDiamond: ["mewtwo", "mew", "raikou", "entei", "suicune", "ho-oh", "regirock", "regice", "registeel", "latias", "latios", "groudon", "kyogre", "rayquaza", "jirachi", "mesprit", "uxie", "azelf", "dialga", "heatran", "regigigas", "giratina", "cresselia", "arceus"],
	shiningPearl: ["articuno", "zapdos", "moltres", "mewtwo", "mew", "raikou", "entei", "suicune", "lugia", "regirock", "regice", "registeel", "latias", "latios", "groudon", "kyogre", "rayquaza", "jirachi", "mesprit", "uxie", "azelf", "palkia", "heatran", "regigigas", "giratina", "cresselia", "arceus"],
	legendsArceus: ["mesprit", "uxie", "azelf", "dialga", "heatran", "regigigas", "giratina", "cresselia", "manaphy", "darkrai", "shaymin", "arceus", "tornadus", "thundurus", "landorus", "enamorus"],
	scarlet: ["koraidon", "wo-chien", "chien-pao", "ting-lu", "chi-yu", "walking-wake"],
	violet: ["miraidon", "wo-chien", "chien-pao", "ting-lu", "chi-yu", "iron-leaves"],
	theTealMask: ["okidogi", "munkidori", "fezandipiti", "ogrepon"],
	theIndigoDisk: ["terapagos", "pecharunt"]
}

export const pokemonPerVersion = {
	red: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "arbok", "raichu", "nidoqueen", "nidoking", "clefable", "wigglytuff", "golbat", "vileplume", "parasect", "venomoth", "dugtrio", "golduck", "primeape", "arcanine", "poliwrath", "alakazam", "machamp", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "weezing", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "scyther", "jynx", "electabuzz", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite"],
	blue: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "raichu", "sandslash", "nidoqueen", "nidoking", "clefable", "ninetales", "wigglytuff", "golbat", "parasect", "venomoth", "dugtrio", "persian", "golduck", "poliwrath", "alakazam", "machamp", "victreebel", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "weezing", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "jynx", "magmar", "pinsir", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite"],
	yellow: ["venusaur", "charizard", "blastoise", "butterfree", "pidgeot", "raticate", "fearow", "pikachu", "sandslash", "nidoqueen", "nidoking", "clefable", "ninetales", "wigglytuff", "golbat", "vileplume", "parasect", "venomoth", "dugtrio", "golduck", "primeape", "arcanine", "poliwrath", "alakazam", "machamp", "victreebel", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "scyther", "pinsir", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite"],
	gold: ["meganium", "typhlosion", "feraligatr", "pidgeot", "fearow", "noctowl", "raticate", "furret", "raichu", "butterfree", "beedrill", "ariados", "golem", "crobat", "clefable", "wigglytuff", "togetic", "sandslash", "arbok", "dunsparce", "ampharos", "quagsire", "gengar", "unown", "steelix", "victreebel", "jumpluff", "parasect", "poliwrath", "politoed", "gyarados", "seaking", "slowbro", "slowking", "vileplume", "bellossom", "hypno", "alakazam", "ditto", "forretress", "nidoqueen", "nidoking", "yanma", "sunflora", "exeggutor", "sudowoodo", "wobbuffet", "venomoth", "scizor", "pinsir", "heracross", "weezing", "muk", "magneton", "electrode", "aipom", "granbull", "arcanine", "stantler", "azumarill", "dugtrio", "primeape", "golduck", "machamp", "hitmonlee", "hitmonchan", "hitmontop", "girafarig", "tauros", "miltank", "magmar", "jynx", "electabuzz", "mr-mime", "smeargle", "farfetchd", "xatu", "qwilfish", "tentacruel", "kingler", "shuckle", "starmie", "cloyster", "corsola", "octillery", "lanturn", "dewgong", "lickitung", "tangela", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "kingdra", "gligar", "piloswine", "ursaring", "mantine", "dodrio", "rapidash", "marowak", "kangaskhan", "rhydon", "murkrow", "houndoom", "magcargo", "sneasel", "misdreavus", "porygon2", "blissey", "lapras", "omastar", "kabutops", "aerodactyl", "snorlax", "venusaur", "charizard", "blastoise", "dragonite", "tyranitar"],
	silver: ["meganium", "typhlosion", "feraligatr", "pidgeot", "fearow", "noctowl", "raticate", "furret", "raichu", "butterfree", "beedrill", "ledian", "golem", "crobat", "clefable", "wigglytuff", "togetic", "sandslash", "arbok", "dunsparce", "ampharos", "quagsire", "gengar", "unown", "steelix", "victreebel", "jumpluff", "parasect", "poliwrath", "politoed", "gyarados", "seaking", "slowbro", "slowking", "vileplume", "bellossom", "hypno", "alakazam", "ditto", "forretress", "nidoqueen", "nidoking", "yanma", "sunflora", "exeggutor", "sudowoodo", "wobbuffet", "venomoth", "scizor", "pinsir", "heracross", "weezing", "muk", "magneton", "electrode", "aipom", "granbull", "ninetales", "stantler", "azumarill", "dugtrio", "persian", "golduck", "machamp", "hitmonlee", "hitmonchan", "hitmontop", "girafarig", "tauros", "miltank", "magmar", "jynx", "electabuzz", "mr-mime", "smeargle", "farfetchd", "xatu", "qwilfish", "tentacruel", "kingler", "shuckle", "starmie", "cloyster", "corsola", "octillery", "lanturn", "dewgong", "lickitung", "tangela", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "kingdra", "delibird", "piloswine", "donphan", "skarmory", "dodrio", "rapidash", "marowak", "kangaskhan", "rhydon", "murkrow", "houndoom", "magcargo", "sneasel", "misdreavus", "porygon2", "blissey", "lapras", "omastar", "kabutops", "aerodactyl", "snorlax", "venusaur", "charizard", "blastoise", "dragonite", "tyranitar"],
	crystal: ["meganium", "typhlosion", "feraligatr", "pidgeot", "fearow", "noctowl", "raticate", "furret", "raichu", "butterfree", "beedrill", "ariados", "ledian", "golem", "crobat", "clefable", "wigglytuff", "togetic", "sandslash", "arbok", "dunsparce", "quagsire", "gengar", "unown", "steelix", "victreebel", "jumpluff", "parasect", "poliwrath", "politoed", "gyarados", "seaking", "slowbro", "slowking", "vileplume", "bellossom", "hypno", "alakazam", "ditto", "forretress", "nidoqueen", "nidoking", "yanma", "sunflora", "exeggutor", "sudowoodo", "wobbuffet", "venomoth", "scizor", "pinsir", "heracross", "weezing", "muk", "magneton", "electrode", "aipom", "granbull", "arcanine", "stantler", "azumarill", "dugtrio", "persian", "golduck", "machamp", "hitmonlee", "hitmonchan", "hitmontop", "tauros", "miltank", "magmar", "jynx", "electabuzz", "mr-mime", "smeargle", "farfetchd", "xatu", "qwilfish", "tentacruel", "kingler", "shuckle", "starmie", "cloyster", "corsola", "lanturn", "dewgong", "lickitung", "tangela", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "kingdra", "gligar", "delibird", "piloswine", "ursaring", "donphan", "mantine", "skarmory", "dodrio", "rapidash", "marowak", "kangaskhan", "rhydon", "murkrow", "houndoom", "magcargo", "sneasel", "misdreavus", "porygon2", "blissey", "lapras", "omastar", "kabutops", "aerodactyl", "snorlax", "venusaur", "charizard", "blastoise", "dragonite", "tyranitar"],
	ruby: ["sceptile", "blaziken", "swampert", "mightyena", "linoone", "beautifly", "dustox", "shiftry", "swellow", "pelipper", "gardevoir", "masquerain", "breloom", "slaking", "alakazam", "ninjask", "shedinja", "exploud", "hariyama", "seaking", "gyarados", "azumarill", "golem", "nosepass", "delcatty", "crobat", "tentacruel", "mawile", "aggron", "machamp", "medicham", "manectric", "plusle", "minun", "magneton", "electrode", "volbeat", "illumise", "vileplume", "bellossom", "dodrio", "roselia", "swalot", "sharpedo", "wailord", "camerupt", "magcargo", "torkoal", "muk", "weezing", "grumpig", "sandslash", "spinda", "skarmory", "flygon", "cacturne", "altaria", "zangoose", "solrock", "whiscash", "crawdaunt", "claydol", "cradily", "armaldo", "wigglytuff", "milotic", "castform", "starmie", "kecleon", "banette", "dusclops", "tropius", "chimecho", "absol", "ninetales", "raichu", "golduck", "wobbuffet", "xatu", "girafarig", "donphan", "pinsir", "heracross", "rhydon", "glalie", "walrein", "huntail", "gorebyss", "relicanth", "corsola", "lanturn", "luvdisc", "kingdra", "salamence", "metagross"],
	sapphire: ["sceptile", "blaziken", "swampert", "mightyena", "linoone", "beautifly", "dustox", "ludicolo", "swellow", "pelipper", "gardevoir", "masquerain", "breloom", "slaking", "alakazam", "ninjask", "shedinja", "exploud", "hariyama", "seaking", "gyarados", "azumarill", "golem", "nosepass", "delcatty", "crobat", "tentacruel", "sableye", "aggron", "machamp", "medicham", "manectric", "plusle", "minun", "magneton", "electrode", "volbeat", "illumise", "vileplume", "bellossom", "dodrio", "roselia", "swalot", "sharpedo", "wailord", "camerupt", "magcargo", "torkoal", "muk", "weezing", "grumpig", "sandslash", "spinda", "skarmory", "flygon", "cacturne", "altaria", "seviper", "lunatone", "whiscash", "crawdaunt", "claydol", "cradily", "armaldo", "wigglytuff", "milotic", "castform", "starmie", "kecleon", "banette", "dusclops", "tropius", "chimecho", "absol", "ninetales", "raichu", "golduck", "wobbuffet", "xatu", "girafarig", "donphan", "pinsir", "heracross", "rhydon", "glalie", "walrein", "huntail", "gorebyss", "relicanth", "corsola", "lanturn", "luvdisc", "kingdra", "salamence", "metagross"],
	emerald: ["sceptile", "blaziken", "swampert", "mightyena", "linoone", "beautifly", "dustox", "ludicolo", "shiftry", "swellow", "pelipper", "gardevoir", "breloom", "slaking", "alakazam", "ninjask", "shedinja", "exploud", "hariyama", "seaking", "gyarados", "azumarill", "golem", "nosepass", "delcatty", "crobat", "tentacruel", "sableye", "mawile", "aggron", "machamp", "manectric", "plusle", "minun", "magneton", "electrode", "volbeat", "illumise", "vileplume", "bellossom", "dodrio", "swalot", "sharpedo", "wailord", "camerupt", "magcargo", "torkoal", "muk", "weezing", "grumpig", "sandslash", "spinda", "skarmory", "flygon", "cacturne", "altaria", "seviper", "solrock", "whiscash", "crawdaunt", "claydol", "cradily", "armaldo", "wigglytuff", "milotic", "castform", "starmie", "kecleon", "banette", "dusclops", "tropius", "chimecho", "absol", "ninetales", "raichu", "golduck", "wobbuffet", "xatu", "girafarig", "donphan", "pinsir", "heracross", "rhydon", "glalie", "walrein", "huntail", "gorebyss", "relicanth", "corsola", "lanturn", "luvdisc", "kingdra", "salamence", "metagross"],
	fireRed: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "arbok", "raichu", "nidoqueen", "nidoking", "clefable", "wigglytuff", "golbat", "vileplume", "parasect", "venomoth", "dugtrio", "golduck", "primeape", "persian", "arcanine", "poliwrath", "alakazam", "machamp", "tentacruel", "golem", "rapidash", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "weezing", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "mr-mime", "scyther", "jynx", "electabuzz", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite"],
	leafGreen: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "raichu", "sandslash", "nidoqueen", "nidoking", "clefable", "ninetales", "wigglytuff", "golbat", "parasect", "venomoth", "dugtrio", "primeape", "persian", "poliwrath", "alakazam", "machamp", "victreebel", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "weezing", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "jynx", "magmar", "pinsir", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite"],
	diamond: ["torterra", "infernape", "empoleon", "staraptor", "bibarel", "kricketune", "luxray", "alakazam", "gyarados", "roserade", "crobat", "golem", "steelix", "rampardos", "machamp", "golduck", "wormadam", "mothim", "beautifly", "dustox", "vespiquen", "pachirisu", "floatzel", "cherrim", "gastrodon", "heracross", "ambipom", "drifblim", "lopunny", "gengar", "honchkrow", "seaking", "whiscash", "chimecho", "skuntank", "medicham", "bronzong", "rapidash", "sudowoodo", "mr-mime", "blissey", "clefable", "chatot", "raichu", "noctowl", "spiritomb", "garchomp", "snorlax", "unown", "lucario", "quagsire", "pelipper", "girafarig", "hippowdon", "azumarill", "drapion", "toxicroak", "dewgong", "scizor", "tyranitar", "mightyena", "aggron", "flygon", "kecleon", "huntail", "gorebyss", "carnivine", "octillery", "lumineon", "tentacruel", "milotic", "mantine", "abomasnow", "weavile", "mamoswine"],
	pearl: ["torterra", "infernape", "empoleon", "staraptor", "bibarel", "kricketune", "luxray", "alakazam", "gyarados", "roserade", "crobat", "golem", "steelix", "bastiodon", "machamp", "golduck", "wormadam", "mothim", "beautifly", "dustox", "vespiquen", "pachirisu", "floatzel", "cherrim", "gastrodon", "heracross", "ambipom", "drifblim", "lopunny", "gengar", "mismagius", "purugly", "seaking", "whiscash", "chimecho", "medicham", "bronzong", "rapidash", "sudowoodo", "mr-mime", "blissey", "clefable", "chatot", "raichu", "noctowl", "spiritomb", "garchomp", "snorlax", "unown", "lucario", "quagsire", "pelipper", "girafarig", "hippowdon", "azumarill", "drapion", "toxicroak", "slowbro", "pinsir", "slowking", "houndoom", "stantler", "flygon", "walrein", "huntail", "gorebyss", "salamence", "carnivine", "octillery", "lumineon", "tentacruel", "milotic", "mantine", "abomasnow", "weavile", "mamoswine"],
	platinum: ["torterra", "infernape", "empoleon", "staraptor", "bibarel", "kricketune", "luxray", "alakazam", "gyarados", "roserade", "crobat", "golem", "steelix", "rampardos", "bastiodon", "machamp", "golduck", "wormadam", "mothim", "beautifly", "dustox", "vespiquen", "pachirisu", "floatzel", "cherrim", "gastrodon", "heracross", "ambipom", "drifblim", "lopunny", "gengar", "seaking", "whiscash", "chimecho", "medicham", "bronzong", "rapidash", "sudowoodo", "mr-mime", "blissey", "clefable", "chatot", "raichu", "noctowl", "spiritomb", "garchomp", "snorlax", "unown", "lucario", "quagsire", "pelipper", "girafarig", "hippowdon", "azumarill", "drapion", "toxicroak", "slowbro", "dewgong", "pinsir", "slowking", "scizor", "houndoom", "stantler", "elekid", "magby", "tyranitar", "mightyena", "aggron", "kecleon", "tropius", "walrein", "salamence", "tangrowth", "electivire", "magmortar", "carnivine", "octillery", "lumineon", "tentacruel", "milotic", "mantine", "abomasnow", "weavile", "mamoswine", "porygon-z"],
	heartGold: ["meganium", "typhlosion", "feraligatr", "pidgeot", "fearow", "noctowl", "raticate", "furret", "raichu", "butterfree", "beedrill", "ariados", "golem", "crobat", "clefable", "wigglytuff", "togetic", "sandslash", "arbok", "dunsparce", "ampharos", "quagsire", "gengar", "unown", "steelix", "victreebel", "jumpluff", "parasect", "poliwrath", "politoed", "gyarados", "seaking", "slowbro", "slowking", "vileplume", "bellossom", "hypno", "alakazam", "ditto", "forretress", "nidoqueen", "nidoking", "yanma", "sunflora", "exeggutor", "sudowoodo", "wobbuffet", "venomoth", "scizor", "pinsir", "heracross", "weezing", "muk", "magneton", "electrode", "aipom", "granbull", "arcanine", "stantler", "azumarill", "dugtrio", "primeape", "golduck", "machamp", "hitmonlee", "hitmonchan", "hitmontop", "girafarig", "tauros", "miltank", "magmortar", "jynx", "electivire", "mr-mime", "smeargle", "farfetchd", "xatu", "qwilfish", "tentacruel", "kingler", "shuckle", "starmie", "cloyster", "corsola", "octillery", "lanturn", "dewgong", "lickitung", "tangrowth", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "kingdra", "gliscor", "mamoswine", "donphan", "mantine", "dodrio", "rapidash", "marowak", "kangaskhan", "rhydon", "honchkrow", "houndoom", "magcargo", "weavile", "mismagius", "porygon-z", "blissey", "lapras", "omastar", "aerodactyl", "snorlax", "venusaur", "charizard", "blastoise", "dragonite", "tyranitar", "claydol", "armaldo"],
	soulSilver: ["meganium", "typhlosion", "feraligatr", "pidgeot", "fearow", "noctowl", "raticate", "furret", "raichu", "butterfree", "beedrill", "ledian", "golem", "crobat", "clefable", "wigglytuff", "togetic", "sandslash", "arbok", "dunsparce", "ampharos", "quagsire", "gengar", "unown", "steelix", "victreebel", "jumpluff", "parasect", "poliwrath", "politoed", "gyarados", "seaking", "slowbro", "slowking", "vileplume", "bellossom", "hypno", "alakazam", "ditto", "forretress", "nidoqueen", "nidoking", "yanma", "sunflora", "exeggutor", "sudowoodo", "wobbuffet", "venomoth", "scizor", "pinsir", "heracross", "weezing", "muk", "magneton", "electrode", "aipom", "granbull", "ninetales", "stantler", "azumarill", "dugtrio", "persian", "golduck", "machamp", "hitmonlee", "hitmonchan", "hitmontop", "girafarig", "tauros", "miltank", "magmortar", "jynx", "electivire", "mr-mime", "smeargle", "farfetchd", "xatu", "qwilfish", "tentacruel", "kingler", "shuckle", "starmie", "cloyster", "corsola", "octillery", "lanturn", "dewgong", "lickitung", "tangrowth", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "kingdra", "delibird", "mamoswine", "ursaring", "skarmory", "dodrio", "rapidash", "marowak", "kangaskhan", "rhydon", "honchkrow", "houndoom", "magcargo", "weavile", "mismagius", "porygon-z", "blissey", "lapras", "kabutops", "aerodactyl", "snorlax", "venusaur", "charizard", "blastoise", "dragonite", "tyranitar", "mawile", "swalot", "cradily"],
	black: ["serperior", "emboar", "samurott", "watchog", "stoutland", "liepard", "simisage", "simisear", "simipour", "musharna", "unfezant", "zebstrika", "gigalith", "swoobat", "excadrill", "audino", "conkeldurr", "seismitoad", "throh", "sawk", "leavanny", "scolipede", "whimsicott", "lilligant", "basculin", "krookodile", "darmanitan", "maractus", "crustle", "scrafty", "sigilyph", "cofagrigus", "carracosta", "archeops", "garbodor", "zoroark", "cinccino", "gothitelle", "swanna", "vanilluxe", "sawsbuck", "emolga", "escavalier", "amoonguss", "jellicent", "alomomola", "galvantula", "ferrothorn", "klinklang", "eelektross", "beheeyem", "chandelure", "haxorus", "beartic", "cryogonal", "accelgor", "stunfisk", "mienshao", "druddigon", "golurk", "bisharp", "bouffalant", "mandibuzz", "heatmor", "durant", "hydreigon", "volcarona", "beedrill", "honchkrow", "houndoom", "breloom", "plusle", "genesect"],
	white: ["serperior", "emboar", "samurott", "watchog", "stoutland", "liepard", "simisage", "simisear", "simipour", "musharna", "unfezant", "zebstrika", "gigalith", "swoobat", "excadrill", "audino", "conkeldurr", "seismitoad", "throh", "sawk", "leavanny", "scolipede", "whimsicott", "lilligant", "basculin", "krookodile", "darmanitan", "maractus", "crustle", "scrafty", "sigilyph", "cofagrigus", "carracosta", "archeops", "garbodor", "zoroark", "cinccino", "reuniclus", "swanna", "vanilluxe", "sawsbuck", "emolga", "escavalier", "amoonguss", "jellicent", "alomomola", "galvantula", "ferrothorn", "klinklang", "eelektross", "beheeyem", "chandelure", "haxorus", "beartic", "cryogonal", "accelgor", "stunfisk", "mienshao", "druddigon", "golurk", "bisharp", "bouffalant", "braviary", "heatmor", "durant", "hydreigon", "volcarona", "butterfree", "parasect", "mismagius", "mightyena", "minun", "genesect"],
	blackTwo: ["serperior", "emboar", "samurott", "watchog", "liepard", "unfezant", "swadloon", "leavanny", "sunflora", "stoutland", "ampharos", "golduck", "azumarill", "lucario", "dunsparce", "audino", "simisage", "simisear", "simipour", "scolipede", "weezing", "magnezone", "arcanine", "magmortar", "raticate", "crobat", "muk", "swoobat", "gigalith", "steelix", "conkeldurr", "excadrill", "lopunny", "whimsicott", "lilligant", "musharna", "clefable", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "krookodile", "darmanitan", "basculin", "garbodor", "cinccino", "mandibuzz", "sandslash", "crustle", "scrafty", "maractus", "sigilyph", "flygon", "cofagrigus", "carracosta", "archeops", "klinklang", "roserade", "gothitelle", "vespiquen", "emolga", "heracross", "pinsir", "zebstrika", "floatzel", "zoroark", "swanna", "escavalier", "accelgor", "sawsbuck", "amoonguss", "castform", "probopass", "aggron", "claydol", "volcarona", "galvantula", "ferrothorn", "eelektross", "jellicent", "alomomola", "haxorus", "zangoose", "seviper",  "beheeyem", "chandelure", "heatmor", "durant", "beartic", "cryogonal", "drapion", "skarmory", "grumpig", "drifblim", "banette", "pelipper", "lunatone", "solrock", "absol", "tangrowth", "mienshao", "gliscor", "bisharp", "seismitoad", "stunfisk", "shuckle", "mantine", "octillery", "corsola", "starmie", "wailord", "lapras", "altaria", "ninetales", "bronzong", "weavile", "delibird", "vanilluxe", "mamoswine", "ditto", "metagross", "dewgong", "throh", "sawk", "bouffalant", "druddigon", "golurk", "hydreigon", "slaking", "crawdaunt", "wigglytuff", "lickilicky", "yanmega", "tropius", "carnivine", "toxicroak", "beedrill", "magmortar", "ariados", "sudowoodo", "plusle", "skuntank", "garchomp", "tyranitar", "genesect"],
	whiteTwo: ["serperior", "emboar", "samurott", "watchog", "liepard", "unfezant", "swadloon", "leavanny", "sunflora", "stoutland", "ampharos", "golduck", "azumarill", "lucario", "dunsparce", "audino", "simisage", "simisear", "simipour", "scolipede", "weezing", "magnezone", "arcanine", "electivire", "raticate", "crobat", "muk", "swoobat", "gigalith", "steelix", "conkeldurr", "excadrill", "delcatty", "whimsicott", "lilligant", "musharna", "clefable", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "krookodile", "darmanitan", "basculin", "garbodor", "cinccino", "braviary", "sandslash", "crustle", "scrafty", "maractus", "sigilyph", "flygon", "cofagrigus", "carracosta", "archeops", "klinklang", "roserade", "reuniclus", "vespiquen", "emolga", "heracross", "pinsir", "zebstrika", "floatzel", "zoroark", "swanna", "escavalier", "accelgor", "sawsbuck", "amoonguss", "castform", "probopass", "aggron", "claydol", "volcarona", "galvantula", "ferrothorn", "eelektross", "jellicent", "alomomola", "haxorus", "zangoose", "seviper",  "beheeyem", "chandelure", "heatmor", "durant", "beartic", "cryogonal", "drapion", "skarmory", "camerupt", "drifblim", "banette", "pelipper", "lunatone", "solrock", "absol", "tangrowth", "mienshao", "gliscor", "bisharp", "seismitoad", "stunfisk", "shuckle", "mantine", "octillery", "corsola", "starmie", "wailord", "lapras", "altaria", "ninetales", "bronzong", "weavile", "delibird", "vanilluxe", "mamoswine", "ditto", "metagross", "dewgong", "throh", "sawk", "bouffalant", "druddigon", "golurk", "hydreigon", "slaking", "crawdaunt", "wigglytuff", "lickilicky", "yanmega", "tropius", "carnivine", "toxicroak", "butterfree", "mr-mime", "ledian",  "minun", "purugly", "tyranitar", "genesect"],
	x: ["chesnaught", "delphox", "greninja",  "diggersby", "linoone", "talonflame", "pidgeot", "vivillon", "butterfree", "beedrill", "simisage", "simisear", "simipour", "raichu", "bibarel", "dunsparce", "azumarill", "wormadam", "mothim", "masquerain", "gyarados", "crawdaunt", "seaking", "sharpedo", "pyroar", "golduck", "farfetchd", "lucario", "gardevoir", "gallade", "florges", "roserade", "ledian", "vespiquen", "delcatty", "venusaur", "charizard", "blastoise", "gogoat", "pangoro", "furfrou", "dodrio", "plusle", "minun", "swalot", "scrafty", "alakazam", "vileplume", "bellossom", "furret", "ninjask", "shedinja", "meowstic", "kecleon", "aegislash", "scolipede", "audino", "smeargle", "toxicroak", "swanna", "slurpuff", "volbeat", "illumise", "jumpluff", "snorlax", "exploud", "medicham", "crobat", "haxorus", "drifblim", "mienshao", "zangoose", "seviper", "grumpig", "absol", "malamar", "lunatone", "solrock", "salamence", "pelipper", "swellow", "barbaracle", "crustle", "tentacruel", "wailord", "luvdisc", "clawitzer", "starmie", "qwilfish", "kingdra", "relicanth", "krookodile", "heliolisk", "hippowdon", "rhyperior", "steelix", "machamp", "marowak", "kangaskhan", "mawile", "tyrantrum", "aurorus", "omastar", "aerodactyl", "ferrothorn", "granbull", "houndoom", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "emolga", "yanmega", "hawlucha", "sigilyph", "golurk", "probopass", "hariyama", "sawk", "staraptor", "skuntank", "nidoqueen", "nidoking", "dedenne", "chimecho", "mr-mime", "reuniclus", "wobbuffet", "gigalith", "sableye", "carbink", "tauros", "miltank", "ampharos", "pinsir", "pachirisu", "slowbro", "slowking", "exeggutor", "chatot", "mantine", "huntail", "gorebyss", "octillery", "corsola", "lanturn", "alomomola", "lapras", "dugtrio", "flygon",
		"garchomp", "golem", "magcargo", "shuckle", "drapion", "quagsire", "goodra", "escavalier", "accelgor", "victreebel", "carnivine", "gengar", "poliwrath", "politoed", "arbok", "stunfisk", "whiscash", "mightyena", "watchog", "bisharp", "klefki", "honchkrow", "amoonguss", "ludicolo", "floatzel", "basculin", "trevenant", "gourgeist", "chandelure", "rotom", "magnezone", "electrode", "garbodor", "mamoswine", "avalugg", "beartic", "jynx", "vanilluxe", "abomasnow", "delibird", "weavile", "conkeldurr", "torkoal", "sandslash", "aggron", "heatmor", "durant", "ariados", "fearow", "cryogonal", "skarmory", "noivern", "gliscor", "noctowl", "wigglytuff", "banette", "zoroark", "gothitelle", "sudowoodo", "spinda", "ursaring", "lickilicky", "scizor", "ditto", "altaria", "cradily", "armaldo", "druddigon", "hydreigon","dragonite"],
	y: ["chesnaught", "delphox", "greninja",  "diggersby", "linoone", "talonflame", "pidgeot", "vivillon", "butterfree", "beedrill", "simisage", "simisear", "simipour", "raichu", "bibarel", "dunsparce", "azumarill", "wormadam", "mothim", "masquerain", "gyarados", "crawdaunt", "seaking", "sharpedo", "pyroar", "golduck", "farfetchd", "lucario", "gardevoir", "gallade", "florges", "roserade", "ledian", "vespiquen", "delcatty", "venusaur", "charizard", "blastoise", "gogoat", "pangoro", "furfrou", "dodrio", "plusle", "minun", "swalot", "scrafty", "alakazam", "vileplume", "bellossom", "furret", "ninjask", "shedinja", "meowstic", "kecleon", "aegislash", "scolipede", "audino", "smeargle", "toxicroak", "swanna", "aromatisse", "volbeat", "illumise", "jumpluff", "snorlax", "exploud", "medicham", "crobat", "haxorus", "drifblim", "mienshao", "zangoose", "seviper", "grumpig", "absol", "malamar", "lunatone", "solrock", "salamence", "pelipper", "swellow", "barbaracle", "crustle", "tentacruel", "wailord", "luvdisc", "dragalge", "cloyster", "qwilfish", "kingdra", "relicanth", "krookodile", "heliolisk", "hippowdon", "rhyperior", "steelix", "machamp", "marowak", "kangaskhan", "mawile", "tyrantrum", "aurorus", "kabutops", "aerodactyl", "ferrothorn", "granbull", "manectric", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "emolga", "yanmega", "hawlucha", "sigilyph", "golurk", "probopass", "hariyama", "throh", "staraptor", "skuntank", "nidoqueen", "nidoking", "dedenne", "chimecho", "mr-mime", "reuniclus", "wobbuffet", "gigalith", "sableye", "carbink", "tauros", "miltank", "ampharos", "heracross", "pachirisu", "slowbro", "slowking", "exeggutor", "chatot", "mantine", "huntail", "gorebyss", "octillery", "corsola", "lanturn", "alomomola", "lapras", "dugtrio",
		"flygon", "garchomp", "golem", "magcargo", "shuckle", "drapion", "quagsire", "goodra", "escavalier", "accelgor", "victreebel", "carnivine", "gengar", "poliwrath", "politoed", "arbok", "stunfisk", "whiscash", "liepard", "watchog", "bisharp", "klefki", "honchkrow", "amoonguss", "ludicolo", "floatzel", "basculin", "trevenant", "gourgeist", "chandelure", "rotom", "magnezone", "electrode", "garbodor", "mamoswine", "avalugg", "beartic", "jynx", "vanilluxe", "abomasnow", "delibird", "weavile", "conkeldurr", "torkoal", "sandslash", "tyranitar", "heatmor", "durant", "ariados", "fearow", "cryogonal", "skarmory", "noivern", "gliscor", "noctowl", "wigglytuff", "banette", "zoroark", "gothitelle", "sudowoodo", "spinda", "ursaring", "lickilicky", "scizor", "ditto", "altaria", "druddigon", "hydreigon","dragonite"],
	omegaRuby: ["sceptile", "blaziken", "swampert", "mightyena", "linoone", "beautifly", "dustox", "shiftry", "swellow", "pelipper", "gardevoir", "gallade", "masquerain", "breloom", "slaking", "alakazam", "ninjask", "shedinja", "exploud", "hariyama", "seaking", "gyarados", "azumarill", "golem", "probopass", "delcatty", "crobat", "tentacruel", "mawile", "aggron", "machamp", "medicham", "manectric", "plusle", "minun", "magnezone", "electrode", "volbeat", "illumise", "oddish", "vileplume", "bellossom", "dodrio", "roserade", "swalot", "sharpedo", "wailord", "camerupt", "magcargo", "torkoal", "muk", "weezing", "grumpig", "sandslash", "spinda", "skarmory", "trapinch", "flygon", "cacturne", "altaria", "seviper", "solrock", "whiscash", "crawdaunt", "claydol", "cradily", "armaldo", "kabutops", "bastiodon", "archeops", "gastrodon", "throh", "dragalge", "wigglytuff", "milotic", "castform", "starmie", "kecleon", "banette", "dusknoir", "tropius", "chimecho", "absol", "ninetales", "raichu", "golduck", "wobbuffet", "xatu", "girafarig", "donphan", "pinsir", "heracross", "rhyhorn", "rhyperior", "glalie", "froslass", "walrein", "huntail", "gorebyss", "relicanth", "corsola", "lanturn", "luvdisc", "kingdra", "salamence", "metagross"],
	alphaSapphire: ["sceptile", "blaziken", "swampert", "mightyena", "linoone", "beautifly", "dustox", "ludicolo", "swellow", "pelipper", "gardevoir", "gallade", "masquerain", "breloom", "slaking", "alakazam", "ninjask", "shedinja", "exploud", "hariyama", "seaking", "gyarados", "azumarill", "golem", "probopass", "delcatty", "crobat", "tentacruel", "sableye", "aggron", "machamp", "medicham", "manectric", "plusle", "minun", "magnezone", "electrode", "volbeat", "illumise", "oddish", "vileplume", "bellossom", "dodrio", "roserade", "swalot", "sharpedo", "wailord", "camerupt", "magcargo", "torkoal", "muk", "weezing", "grumpig", "sandslash", "spinda", "skarmory", "trapinch", "flygon", "cacturne", "altaria", "seviper", "lunatone", "whiscash", "crawdaunt", "claydol", "cradily", "armaldo", "omastar", "rampardos", "carracosta", "gastrodon", "sawk", "clawitzer", "wigglytuff", "milotic", "castform", "starmie", "kecleon", "banette", "dusknoir", "tropius", "chimecho", "absol", "ninetales", "raichu", "golduck", "wobbuffet", "xatu", "girafarig", "donphan", "pinsir", "heracross", "rhyhorn", "rhyperior", "glalie", "froslass", "walrein", "huntail", "gorebyss", "relicanth", "corsola", "lanturn", "luvdisc", "kingdra", "salamence", "metagross"],
	sun: ["decidueye", "incineroar", "primarina", "toucannon", "gumshoos", "raticate", "butterfree", "ledian", "ariados", "lopunny", "malamar", "zoroark", "furfrou", "raichu", "vikavolt", "sudowoodo", "blissey", "snorlax", "slowbro", "slowking", "pelipper", "alakazam", "persian", "magnezone", "muk", "mr-mime", "arbok", "dunsparce", "arcanine", "hypno", "hariyama", "smeargle", "crabominable", "gengar", "drifblim", "honchkrow", "crobat", "noivern", "dugtrio", "fearow", "braviary", "primeape", "delibird", "hawlucha", "oricorio", "ribombee", "florges", "whimsicott", "golduck", "jynx", "gyarados", "whiscash", "dewgong", "machamp", "gigalith", "carbink", "sableye", "mawile", "lycanroc", "spinda", "tentacruel", "lumineon", "wishiwashi", "luvdisc", "corsola", "toxapex", "cloyster", "huntail", "gorebyss", "octillery", "mantine", "salamence", "stoutland", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "ampharos", "mudsdale", "wigglytuff", "tauros", "miltank", "masquerain", "araquanid", "lurantis", "shiinotic", "parasect", "poliwrath", "politoed", "seaking", "basculin", "milotic", "alomomola", "talonflame", "salazzle", "marowak", "kangaskhan", "magmortar", "volcarona", "bewear", "tsareena", "comfey", "pinsir", "noctowl", "kecleon", "passimian", "goodra", "castform", "golisopod", "starmie", "palossand", "omastar", "kabutops", "cradily", "armaldo", "rampardos", "carracosta", "tyrantrum", "aurorus", "tyranitar", "trevenant", "xatu", "probopass", "pyukumuku", "lanturn", "silvally", "naganadel", "garbodor", "cinccino", "forretress", "skarmory", "ditto", "clefable", "beheeyem", "minior", "metagross", "porygon-z", "pangoro", "komala", "torkoal", "turtonator", "houndoom", "dedenne",
		"togedemaru", "manectric", "electivire", "golem", "krookodile", "flygon", "garchomp", "claydol", "golurk", "klefki", "mimikyu", "banette", "jellicent", "bruxish", "absol", "glalie", "froslass", "weavile", "ninetales", "vanilluxe", "scrafty", "bisharp", "granbull", "gastrodon", "relicanth", "dhelmise", "sharpedo", "dragalge", "clawitzer", "wailord", "lapras", "tropius", "exeggutor", "crawdaunt", "mienshao", "kommo-o", "emolga", "scizor", "heracross", "ambipom", "pyroar", "mismagius", "druddigon", "lickilicky", "lucario", "dragonite", "aerodactyl", "nihilego", "stakataka", "blacephalon", "buzzwole", "xurkitree", "kartana", "guzzlord", "magearna", "marshadow", "zeraora"],
	moon: ["decidueye", "incineroar", "primarina", "toucannon", "gumshoos", "raticate", "butterfree", "ledian", "ariados", "lopunny", "malamar", "zoroark", "furfrou", "raichu", "vikavolt", "sudowoodo", "blissey", "snorlax", "slowbro", "slowking", "pelipper", "alakazam", "persian", "magnezone", "muk", "mr-mime", "arbok", "dunsparce", "arcanine", "hypno", "hariyama", "smeargle", "crabominable", "gengar", "drifblim", "honchkrow", "crobat", "noivern", "dugtrio", "fearow", "mandibuzz", "primeape", "delibird", "hawlucha", "oricorio", "ribombee", "florges", "lilligant", "golduck", "jynx", "gyarados", "whiscash", "dewgong", "machamp", "gigalith", "carbink", "sableye", "mawile", "lycanroc", "spinda", "tentacruel", "lumineon", "wishiwashi", "luvdisc", "corsola", "toxapex", "cloyster", "huntail", "gorebyss", "octillery", "mantine", "salamence", "stoutland", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "ampharos", "mudsdale", "wigglytuff", "tauros", "miltank", "masquerain", "araquanid", "lurantis", "shiinotic", "parasect", "poliwrath", "politoed", "seaking", "basculin", "milotic", "alomomola", "talonflame", "salazzle", "marowak", "kangaskhan", "magmortar", "volcarona", "bewear", "tsareena", "comfey", "pinsir", "noctowl", "kecleon", "oranguru", "goodra", "castform", "golisopod", "starmie", "palossand", "omastar", "kabutops", "cradily", "armaldo", "bastiodon", "archeops", "tyrantrum", "aurorus", "tyranitar", "trevenant", "xatu", "probopass", "pyukumuku", "lanturn", "silvally", "naganadel", "garbodor", "cinccino", "forretress", "skarmory", "ditto", "clefable", "beheeyem", "minior", "metagross", "porygon-z", "pangoro", "komala", "torkoal", "houndoom", "dedenne",
		"togedemaru", "manectric", "electivire", "golem", "krookodile", "flygon", "garchomp", "claydol", "golurk", "klefki", "mimikyu", "banette", "jellicent", "bruxish", "drampa", "absol", "glalie", "froslass", "weavile", "sandslash", "vanilluxe", "scrafty", "bisharp", "granbull", "gastrodon", "relicanth", "dhelmise", "sharpedo", "dragalge", "clawitzer", "wailord", "lapras", "tropius", "exeggutor", "crawdaunt", "mienshao", "kommo-o", "emolga", "scizor", "heracross", "ambipom", "pyroar", "mismagius", "druddigon", "lickilicky", "lucario", "dragonite", "aerodactyl", "nihilego", "stakataka", "blacephalon", "pheromosa", "xurkitree", "celesteela", "guzzlord", "magearna", "marshadow", "zeraora"],
	ultraSun: ["decidueye", "incineroar", "primarina", "toucannon", "gumshoos", "raticate", "butterfree", "ledian", "ariados", "raichu", "vikavolt", "sudowoodo", "blissey", "snorlax", "slowbro", "slowking", "pelipper", "alakazam", "persian", "magnezone", "muk", "arcanine", "hypno", "hariyama", "smeargle", "crabominable", "gengar", "drifblim", "mismagius", "crobat", "dugtrio", "fearow", "braviary", "primeape", "delibird", "oricorio", "ribombee", "whimsicott", "golduck", "gyarados", "whiscash", "machamp", "gigalith", "carbink", "sableye", "lycanroc", "spinda", "tentacruel", "lumineon", "wishiwashi", "luvdisc", "corsola", "toxapex", "cloyster", "salamence", "stoutland", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "mudsdale", "wigglytuff", "tauros", "miltank", "masquerain", "araquanid", "lurantis", "shiinotic", "parasect", "poliwrath", "politoed", "seaking", "milotic", "alomomola", "talonflame", "salazzle", "marowak", "kangaskhan", "magmortar", "bewear", "tsareena", "comfey", "pinsir", "passimian", "goodra", "castform", "golisopod", "starmie", "palossand", "rampardos", "bastiodon", "archeops", "carracosta", "trevenant", "probopass", "pyukumuku", "lanturn", "silvally", "garbodor", "skarmory", "ditto", "clefable", "minior", "metagross", "porygon-z", "pangoro", "komala", "torkoal", "turtonator", "houndoom", "togedemaru", "electivire", "golem", "krookodile", "flygon", "garchomp", "golurk", "klefki", "mimikyu", "bruxish", "absol", "glalie", "froslass", "weavile", "ninetales", "vanilluxe", "granbull", "gastrodon", "relicanth", "dhelmise", "sharpedo", "clawitzer", "wailord", "lapras", "exeggutor", "kommo-o", "emolga", "scizor", "honchkrow", "lucario", "dragonite", "aerodactyl", "nihilego", "buzzwole", "xurkitree", "kartana", "guzzlord", "magearna", "blacephalon", "marshadow"],
	ultraMoon: ["decidueye", "incineroar", "primarina", "toucannon", "gumshoos", "raticate", "butterfree", "ledian", "ariados", "raichu", "vikavolt", "sudowoodo", "blissey", "snorlax", "slowbro", "slowking", "pelipper", "alakazam", "persian", "magnezone", "muk", "arcanine", "hypno", "hariyama", "smeargle", "crabominable", "gengar", "drifblim", "mismagius", "crobat", "dugtrio", "fearow", "mandibuzz", "primeape", "delibird", "oricorio", "ribombee", "lilligant", "golduck", "gyarados", "whiscash", "machamp", "gigalith", "carbink", "sableye", "lycanroc", "spinda", "tentacruel", "lumineon", "wishiwashi", "luvdisc", "corsola", "toxapex", "cloyster", "salamence", "stoutland", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "mudsdale", "wigglytuff", "tauros", "miltank", "masquerain", "araquanid", "lurantis", "shiinotic", "parasect", "poliwrath", "politoed", "seaking", "milotic", "alomomola", "talonflame", "salazzle", "marowak", "kangaskhan", "magmortar", "bewear", "tsareena", "comfey", "pinsir", "oranguru", "goodra", "castform", "golisopod", "starmie", "palossand", "rampardos", "bastiodon", "archeops", "carracosta", "trevenant", "probopass", "pyukumuku", "lanturn", "silvally", "garbodor", "skarmory", "ditto", "clefable", "minior", "metagross", "porygon-z", "pangoro", "komala", "torkoal", "manectric", "togedemaru", "electivire", "golem", "krookodile", "flygon", "garchomp", "claydol", "klefki", "mimikyu", "bruxish", "drampa", "absol", "glalie", "froslass", "weavile", "sandslash", "vanilluxe", "granbull", "gastrodon", "relicanth", "dhelmise", "sharpedo", "dragalge", "wailord", "lapras", "exeggutor", "kommo-o", "emolga", "scizor", "honchkrow", "lucario", "dragonite", "aerodactyl", "nihilego", "pheromosa", "xurkitree", "celesteela", "guzzlord", "magearna", "stakataka", "marshadow"],
	letsGoPikachu: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "pikachu", "sandslash", "nidoqueen", "nidoking", "clefable", "wigglytuff", "golbat", "vileplume", "parasect", "venomoth", "dugtrio", "golduck", "primeape", "arcanine", "poliwrath", "alakazam", "machamp", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "muk", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "scyther", "jynx", "electabuzz", "magmar", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite", "melmetal"],
	letsGoEevee: ["venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "raticate", "fearow", "arbok", "raichu", "nidoqueen", "nidoking", "clefable", "ninetales", "wigglytuff", "golbat", "parasect", "venomoth", "dugtrio", "persian", "golduck", "poliwrath", "alakazam", "machamp", "victreebel", "tentacruel", "golem", "rapidash", "slowbro", "magneton", "farfetchd", "dodrio", "dewgong", "cloyster", "gengar", "onix", "hypno", "kingler", "electrode", "exeggutor", "marowak", "hitmonlee", "hitmonchan", "lickitung", "weezing", "rhydon", "chansey", "tangela", "kangaskhan", "seadra", "seaking", "starmie", "mr-mime", "jynx", "electabuzz", "magmar", "pinsir", "tauros", "gyarados", "lapras", "ditto", "vaporeon", "jolteon", "flareon", "porygon", "omastar", "kabutops", "aerodactyl", "snorlax", "dragonite", "melmetal"],
	sword: ["rillaboom", "cinderace", "inteleon", "orbeetle", "butterfree", "vikavolt", "noctowl", "corviknight", "greedent", "unfezant", "thievul", "obstagoon", "dubwool", "shiftry", "drednaw", "liepard", "boltund", "diggersby", "cinccino", "tsareena", "vileplume", "bellossom", "roserade", "pelipper", "galvantula", "manectric", "ninetales", "arcanine", "vanilluxe", "mamoswine", "delibird", "glalie", "froslass", "claydol", "mudsdale", "crustle", "golurk", "musharna", "xatu", "bewear", "abomasnow", "kingler", "quagsire", "crawdaunt", "ninjask", "shedinja", "hitmonlee", "hitmonchan", "hitmontop", "pangoro", "klinklang", "vespiquen", "bronzong", "gardevoir", "gallade", "drifblim", "eldegoss", "cherrim", "skuntank", "seismitoad", "dusknoir", "machamp", "gengar", "gyarados", "seaking", "octillery", "cloyster", "milotic", "basculin", "wishiwashi", "pyukumuku", "garbodor", "centiskorch", "coalossal", "dugtrio", "excadrill", "gigalith", "conkeldurr", "swoobat", "noivern", "steelix", "barraskewda", "perrserker", "persian", "alcremie", "ribombee", "ferrothorn", "gourgeist", "raichu", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "flapple", "meowstic", "slurpuff", "araquanid", "wobbuffet", "sirfetchd", "lanturn", "scrafty", "stunfisk", "shuckle", "whiscash", "gastrodon", "golisopod", "barbaracle", "grimmsnarl", "hatterene", "salazzle", "bisharp", "throh", "sawk", "weezing", "sudowoodo", "clefable", "togekiss", "snorlax", "whimsicott", "rhyperior", "gothitelle", "escavalier", "accelgor", "beheeyem", "beartic", "braviary", "drapion", "chandelure", "malamar", "weavile", "mawile", "maractus", "sigilyph", "lucario", "torkoal", "mimikyu", "copperajah", "qwilfish", "jellicent", "toxapex", "cramorant", "toxtricity", "sandaconda", "hippowdon", "durant", "heatmor", "heliolisk", "hawlucha", "flygon", "haxorus", "runerigus", "cofagrigus", "aegislash", "polteageist", "indeedee", "trevenant", "shiinotic", "passimian", "morpeko", "falinks", "turtonator", "togedemaru", "hydreigon", "kommo-o", "solrock", "darmanitan", "stonjourner"],
	shield: ["rillaboom", "cinderace", "inteleon", "orbeetle", "butterfree", "vikavolt", "noctowl", "corviknight", "greedent", "unfezant", "thievul", "obstagoon", "dubwool", "ludicolo", "drednaw", "liepard", "boltund", "diggersby", "cinccino", "tsareena", "vileplume", "bellossom", "roserade", "pelipper", "galvantula", "manectric", "ninetales", "arcanine", "vanilluxe", "mamoswine", "delibird", "glalie", "froslass", "claydol", "mudsdale", "crustle", "golurk", "musharna", "xatu", "bewear", "abomasnow", "kingler", "quagsire", "crawdaunt", "ninjask", "shedinja", "hitmonlee", "hitmonchan", "hitmontop", "pangoro", "klinklang", "vespiquen", "bronzong", "gardevoir", "gallade", "drifblim", "eldegoss", "cherrim", "skuntank", "seismitoad", "dusknoir", "machamp", "gengar", "gyarados", "seaking", "octillery", "cloyster", "milotic", "basculin", "wishiwashi", "pyukumuku", "garbodor", "centiskorch", "coalossal", "dugtrio", "excadrill", "gigalith", "conkeldurr", "swoobat", "noivern", "steelix", "barraskewda", "perrserker", "persian", "alcremie", "ribombee", "ferrothorn", "gourgeist", "raichu", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "appletun", "meowstic", "aromatisse", "araquanid", "wobbuffet", "lanturn", "toxicroak", "stunfisk", "shuckle", "whiscash", "gastrodon", "golisopod", "barbaracle", "cursola", "grimmsnarl", "hatterene", "salazzle", "bisharp", "throh", "sawk", "weezing", "sudowoodo", "clefable", "togekiss", "snorlax", "whimsicott", "rhyperior", "reuniclus", "escavalier", "accelgor", "beheeyem", "beartic", "mandibuzz", "drapion", "chandelure", "malamar", "weavile", "sableye", "maractus", "sigilyph", "lucario", "torkoal", "mimikyu", "copperajah", "qwilfish", "jellicent", "toxapex", "cramorant", "toxtricity", "sandaconda", "hippowdon", "durant", "heatmor", "heliolisk", "hawlucha", "flygon", "haxorus", "runerigus", "cofagrigus", "aegislash", "rapidash", "polteageist", "indeedee", "trevenant", "shiinotic", "passimian", "morpeko", "falinks", "drampa", "togedemaru", "tyranitar", "goodra", "lunatone", "eiscue"],
	isleOfArmor: {
		sword: ["slowbro", "slowking", "lopunny", "blissey", "skwovet", "wigglytuff", "lurantis", "talonflame", "luxray", "klefki", "alakazam", "tentacruel", "dunsparce", "bouffalant", "lickilicky", "druddigon", "venusaur", "blastoise", "scolipede", "amoonguss", "comfey", "tangrowth", "zoroark", "starmie", "urshifu", "emolga", "dedenne", "magnezone", "sharpedo", "stoutland", "tauros", "miltank", "scizor", "pinsir", "palossand", "azumarill", "poliwrath", "politoed", "golduck", "exploud", "skarmory", "lycanroc", "mienshao", "sandslash", "marowak", "kangaskhan", "krookodile", "volcarona", "clawitzer", "kingdra", "lilligant", "exeggutor", "porygon-z", "zarude", "jynx", "electivire", "magmortar", "audino", "cryogonal", "altaria", "spiritomb", "nidoqueen", "nidoking", "tyrantrum", "aurorus", "absol", "aerodactyl", "carbink", "metagross", "crobat", "carracosta", "archeops", "walrein", "cradily", "armaldo", "relicanth", "aggron", "dragonite"],
		shield: ["slowbro", "slowking", "lopunny", "blissey", "skwovet", "wigglytuff", "lurantis", "talonflame", "luxray", "klefki", "alakazam", "tentacruel", "dunsparce", "bouffalant", "lickilicky", "druddigon", "venusaur", "blastoise", "scolipede", "amoonguss", "comfey", "tangrowth", "zoroark", "starmie", "urshifu", "emolga", "dedenne", "magnezone", "sharpedo", "stoutland", "tauros", "miltank", "scizor", "heracross", "palossand", "azumarill", "poliwrath", "politoed", "golduck", "exploud", "skarmory", "lycanroc", "mienshao", "sandslash", "marowak", "kangaskhan", "krookodile", "volcarona", "dragalge", "kingdra", "lilligant", "exeggutor", "porygon-z", "zarude", "jynx", "electivire", "magmortar", "audino", "cryogonal", "altaria", "spiritomb", "nidoqueen", "nidoking", "tyrantrum", "aurorus", "absol", "aerodactyl", "carbink", "metagross", "crobat", "carracosta", "archeops", "walrein", "cradily", "armaldo", "relicanth", "aggron", "dragonite"]
	},
	crownOfTundra: {
		sword: ["frosmoth", "grapploct", "pincurchin", "mantine", "wailord", "avalugg", "dhelmise", "lapras", "mr-rime", "duraludon", "rotom", "ditto", "dracozolt", "arctozolt", "dracovish", "arctovish", "charizard", "silvally", "dragapult", "omastar", "salamence"],
		shield: ["frosmoth", "grapploct", "pincurchin", "mantine", "wailord", "avalugg", "dhelmise", "lapras", "mr-rime", "duraludon", "rotom", "ditto", "dracozolt", "arctozolt", "dracovish", "arctovish", "charizard", "silvally", "dragapult", "kabutops", "garchomp"]
	},
	brilliantDiamond: ["torterra", "infernape", "empoleon", "staraptor", "bibarel", "kricketune", "butterfree", "luxray", "alakazam", "gyarados", "arbok", "arcanine", "dewgong", "roserade", "crobat", "golem", "steelix", "rampardos", "machamp", "golduck", "wormadam", "mothim", "beautifly", "dustox", "vespiquen", "pachirisu", "floatzel", "cherrim", "gastrodon", "heracross", "ambipom", "drifblim", "lopunny", "gengar", "honchkrow", "seaking", "whiscash", "chimecho", "skuntank", "medicham", "bronzong", "rapidash", "sudowoodo", "mr-mime", "blissey", "clefable", "chatot", "raichu", "noctowl", "spiritomb", "garchomp", "snorlax", "unown", "lucario", "quagsire", "pelipper", "girafarig", "hippowdon", "azumarill", "drapion", "toxicroak", "carnivine", "octillery", "lumineon", "tentacruel", "milotic", "mantine", "abomasnow", "weavile", "rotom", "gliscor", "probopass", "gardevoir", "gallade", "lickilicky", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "altaria", "togekiss", "houndoom", "magnezone", "tangrowth", "yanmega", "tropius", "rhyperior", "dusknoir", "porygon-z", "scizor", "electivire", "kecleon", "shiftry", "mawile", "zangoose", "solrock", "mamoswine", "glalie", "froslass", "absol"],
	shiningPearl: ["torterra", "infernape", "empoleon", "staraptor", "bibarel", "kricketune", "beedrill", "luxray", "alakazam", "gyarados", "sandslash", "ninetales", "slowbro", "slowking", "roserade", "crobat", "golem", "steelix", "bastiodon", "machamp", "golduck", "wormadam", "mothim", "beautifly", "dustox", "vespiquen", "pachirisu", "floatzel", "cherrim", "gastrodon", "heracross", "ambipom", "drifblim", "lopunny", "gengar", "mismagius", "purugly", "seaking", "whiscash", "chimecho", "medicham", "bronzong", "rapidash", "sudowoodo", "mr-mime", "blissey", "clefable", "chatot", "raichu", "noctowl", "spiritomb", "garchomp", "snorlax", "unown", "lucario", "quagsire", "pelipper", "girafarig", "hippowdon", "azumarill", "drapion", "toxicroak", "carnivine", "octillery", "lumineon", "tentacruel", "milotic", "mantine", "abomasnow", "weavile", "rotom", "probopass", "gardevoir", "gallade", "lickilicky", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "altaria", "togekiss", "houndoom", "magnezone", "tangrowth", "yanmega", "tropius", "rhyperior", "dusknoir", "porygon-z", "pinsir", "magmortar", "ursaring", "stantler", "ludicolo", "sableye", "seviper", "mamoswine", "glalie", "froslass", "absol", "salamence"],
	legendsArceus: ["decidueye", "typhlosion", "samurott", "bibarel", "staraptor", "luxray", "beautifly", "dustox", "rapidash", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "crobat", "drifblim", "kricketune", "floatzel", "wormadam", "mothim", "golem", "wyrdeer", "snorlax", "parasect", "raichu", "alakazam", "infernape", "lopunny", "cherrim", "golduck", "vespiquen", "kleavor", "scizor", "heracross", "mr-mime", "ambipom", "gyarados", "gastrodon", "overqwil", "blissey", "roserade", "carnivine", "lilligant", "tangrowth", "whiscash", "toxicroak", "gardevoir", "gallade", "yanmega", "hippowdon", "pachirisu", "skuntank", "ursaluna", "goodra", "steelix", "rhyperior", "sudowoodo", "lickilicky", "togekiss", "torterra", "porygon-z", "gengar", "spiritomb", "honchkrow", "unown", "walrein", "octillery", "drapion", "arcanine", "purugly", "machamp", "chatot", "dusknoir", "empoleon", "mantine", "basculegion", "ninetales", "tentacruel", "lumineon", "magmortar", "magnezone", "bronzong", "electivire", "gliscor", "garchomp", "probopass", "electrode", "rotom", "chimecho", "mismagius", "clefable", "sneasler", "weavile", "glalie", "froslass", "rampardos", "bastiodon", "mamoswine", "avalugg", "abomasnow", "zoroark", "braviary", "lucario"],
	scarlet: ["meowscarada", "skeledirge", "quaquaval", "oinkologne", "spidops", "lokix", "jumpluff", "talonflame", "pawmot", "houndoom", "gumshoos", "greedent", "sunflora", "kricketune", "vivillon", "vespiquen", "corviknight", "blissey", "azumarill", "masquerain", "floatzel", "clodsire", "golduck", "drednaw", "wigglytuff", "gardevoir", "gallade", "hypno", "gengar", "maushold", "raichu", "dachsbun", "slaking", "tsareena", "arboliva", "sudowoodo", "lycanroc", "coalossal", "luxray", "staraptor", "oricorio", "ampharos", "lilligant", "breloom", "flapple", "appletun", "grumpig", "squawkabilly", "hariyama", "crabominable", "salazzle", "donphan", "copperajah", "garchomp", "garganacl", "pelipper", "gyarados", "barraskewda", "basculin", "persian", "drifblim", "florges", "dugtrio", "torkoal", "camerupt", "bronzong", "haxorus", "annihilape", "medicham", "lucario", "ceruledge", "whiscash", "bellibolt", "goodra", "toxicroak", "kilowattrel", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "dudunsparce", "sawsbuck", "farigiraf", "muk", "mabosstiff", "toxtricity", "dedenne", "pachirisu", "grafaiai", "stantler", "amoonguss", "electrode", "magnezone", "ditto", "arcanine", "ursaring", "zangoose", "seviper", "altaria", "gogoat", "tauros", "pyroar", "skuntank", "zoroark", "weavile", "honchkrow", "gothitelle", "polteageist", "mimikyu", "klefki", "indeedee", "brambleghast", "toedscruel", "tropius", "lurantis", "klawf", "scovillain", "cacturne", "rabsca", "venomoth", "forretress", "scizor", "heracross", "espathra", "hippowdon", "krookodile", "sandaconda", "mudsdale", "volcarona", "tinkaton", "hatterene", "grimmsnarl", "wugtrio", "bombirdier", "palafin", "revavroom", "cyclizar", "orthworm", "sableye", "banette", "falinks", "hawlucha", "spiritomb", "noivern", "glimmora", "rotom", "houndstone", "oranguru", "komala", "tyranitar", "stonjourner", "pincurchin", "palossand", "slowbro", "slowking", "gastrodon", "cloyster", "qwilfish", "luvdisc", "lumineon", "bruxish",
		"alomomola", "dragalge", "eelektross", "toxapex", "flamigo", "dragonite", "frosmoth", "abomasnow", "delibird", "beartic", "glalie", "froslass", "cryogonal", "cetitan", "avalugg", "braviary", "kingambit", "hydreigon", "veluza", "dondozo", "tatsugiri", "great-tusk", "scream-tail", "brute-bonnet", "flutter-mane", "slither-wing", "sandy-shocks", "baxcalibur", "gholdengo", "roaring-moon"],
	violet: ["meowscarada", "skeledirge", "quaquaval", "oinkologne", "spidops", "lokix", "jumpluff", "talonflame", "pawmot", "houndoom", "gumshoos", "greedent", "sunflora", "kricketune", "vivillon", "vespiquen", "corviknight", "blissey", "azumarill", "masquerain", "floatzel", "clodsire", "golduck", "drednaw", "wigglytuff", "gardevoir", "gallade", "hypno", "gengar", "maushold", "raichu", "dachsbun", "slaking", "tsareena", "arboliva", "sudowoodo", "lycanroc", "coalossal", "luxray", "staraptor", "oricorio", "ampharos", "lilligant", "breloom", "flapple", "appletun", "grumpig", "squawkabilly", "mismagius", "hariyama", "crabominable", "salazzle", "donphan", "copperajah", "garchomp", "garganacl", "pelipper", "gyarados", "barraskewda", "basculin", "swalot", "persian", "florges", "dugtrio", "torkoal", "camerupt", "bronzong", "haxorus", "annihilape", "medicham", "lucario", "ceruledge", "whiscash", "bellibolt", "goodra", "toxicroak", "kilowattrel", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon", "sylveon", "dudunsparce", "sawsbuck", "farigiraf", "muk", "mabosstiff", "toxtricity", "dedenne", "pachirisu", "grafaiai", "stantler", "amoonguss", "electrode", "magnezone", "ditto", "arcanine", "ursaring", "zangoose", "seviper", "altaria", "gogoat", "tauros", "pyroar", "zoroark", "weavile", "honchkrow", "gothitelle", "polteageist", "mimikyu", "klefki", "indeedee", "brambleghast", "toedscruel", "tropius", "lurantis", "klawf", "scovillain", "cacturne", "rabsca", "venomoth", "forretress", "scizor", "heracross", "espathra", "hippowdon", "krookodile", "sandaconda", "mudsdale", "volcarona", "salamence", "tinkaton", "hatterene", "grimmsnarl", "wugtrio", "bombirdier", "palafin", "revavroom", "cyclizar", "orthworm", "sableye", "banette", "falinks", "hawlucha", "spiritomb", "noivern", "dragapult", "glimmora", "rotom", "houndstone", "passimian", "komala", "eiscue", "pincurchin", "palossand", "slowbro", "slowking", "gastrodon", "cloyster", "qwilfish", "luvdisc", "lumineon", "bruxish",
		"alomomola", "clawitzer", "eelektross", "toxapex", "flamigo", "dragonite", "frosmoth", "abomasnow", "delibird", "beartic", "glalie", "froslass", "cryogonal", "cetitan", "avalugg", "braviary", "kingambit", "veluza", "dondozo", "tatsugiri", "iron-treads", "iron-bundle", "iron-hands", "iron-jugulis", "iron-moth", "iron-thorns", "baxcalibur", "gholdengo", "iron-valiant"],
	theTealMask: {
		scarlet: ["ariados", "yanmega", "quagsire", "mightyena", "volbeat", "illumise", "crawdaunt", "leavanny", "ribombee", "arbok", "victreebel", "furret", "ninetales", "poliwrath", "politoed", "noctowl", "mamoswine", "shiftry", "trevenant", "sinistcha", "golem", "conkeldurr", "snorlax", "ludicolo", "probopass", "vikavolt", "sandslash", "gliscor", "mandibuzz", "kommo-o", "weezing", "mienshao", "dusknoir", "chimecho", "magcargo", "chandelure", "clefable", "milotic", "carbink", "swanna", "cramorant", "basculegion", "ursaluna", "okidogi", "munkidori", "fezandipiti", "ogerpon"],
		violet: ["ariados", "yanmega", "quagsire", "mightyena", "volbeat", "illumise", "crawdaunt", "leavanny", "ribombee", "arbok", "victreebel", "furret", "ninetales", "poliwrath", "politoed", "noctowl", "ambipom", "mamoswine", "shiftry", "trevenant", "sinistcha", "golem", "conkeldurr", "morpeko", "snorlax", "ludicolo", "probopass", "vikavolt", "sandslash", "mandibuzz", "kommo-o", "weezing", "mienshao", "dusknoir", "chimecho", "magcargo", "chandelure", "clefable", "milotic", "carbink", "swanna", "basculegion", "ursaluna", "okidogi", "munkidori", "fezandipiti", "ogerpon"]
	},
	theIndigoDisk: {
		scarlet: ["dodrio", "exeggutor", "rhyperior", "electivire", "magmortar", "kleavor", "zebstrika", "smeargle", "alcremie", "flygon", "toucannon", "tentacruel", "kingdra", "whimsicott", "comfey", "vileplume", "bellossom", "lanturn", "malamar", "araquanid", "hitmonlee", "hitmonchan", "hitmontop", "excadrill", "meowstic", "minior", "rampardos", "cinccino", "skarmory", "plusle", "minun", "scrafty", "golurk", "porygon-z", "galvantula", "metagross", "dewgong", "lapras", "overqwil", "reuniclus", "granbull", "archaludon", "hydrapple", "venusaur", "charizard", "blastoise", "meganium", "typhlosion", "feraligatr", "sceptile", "blaziken", "swampert", "torterra", "infernape", "empoleon", "serperior", "emboar", "samurott", "chesnaught", "delphox", "greninja", "decidueye", "incineroar", "primarina", "rillaboom", "cinderace", "inteleon", "gouging-fire", "raging-bolt"],
		violet: ["dodrio", "exeggutor", "rhyperior", "electivire", "magmortar", "kleavor", "zebstrika", "smeargle", "alcremie", "flygon", "toucannon", "tentacruel", "kingdra", "whimsicott", "comfey", "vileplume", "bellossom", "lanturn", "malamar", "araquanid", "hitmonlee", "hitmonchan", "hitmontop", "excadrill", "meowstic", "minior", "bastiodon", "cinccino", "skarmory", "plusle", "minun", "scrafty", "golurk", "porygon-z", "galvantula", "metagross", "dewgong", "lapras", "overqwil", "reuniclus", "granbull", "archaludon", "hydrapple", "venusaur", "charizard", "blastoise", "meganium", "typhlosion", "feraligatr", "sceptile", "blaziken", "swampert", "torterra", "infernape", "empoleon", "serperior", "emboar", "samurott", "chesnaught", "delphox", "greninja", "decidueye", "incineroar", "primarina", "rillaboom", "cinderace", "inteleon", "iron-crown", "iron-boulder"]
	}
}
export default versions;